common: &common
  adapter: postgresql
  encoding: utf8
  username: mao

development:
  <<: *common
  database: house_development

test: &test
  <<: *common
  database: house_test

production:
  <<: *common
  database: house_production